config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  get '/visitors/:id/picture' => 'visitors#picture', as: :visitor_picture
  root :to => redirect('/visitors')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/typeform.rb
class Typeform < ApplicationRecord
	has_one :visitor
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  include HTTParty
  format :json

  belongs_to :typeform

  def self.visitor_typeform_results
    fetch_url = "https://api.typeform.com/v1/form/#{ENV['VISITOR_DEMOGRAPHIC_TYPEFORM_UID']}?key=#{ENV['TYPEFORM_API_KEY']}"
    response = HTTParty.get(fetch_url)
    return JSON.parse(response.body)["responses"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  include VisitorsHelper
  before_action :set_visitor, only: [:edit, :update, :destroy, :picture]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
    @visitorz = only_completed_survey_results(Visitor.visitor_typeform_results)
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    # raise "hello"
    @visitor = Visitor.find(params[:id])
    @visitorz = only_completed_survey_results(Visitor.visitor_typeform_results)
    @visitorr = survey_based_on_token(@visitorz, @visitor.typeform.token).first
    # raise "hi"
  end
  
  def picture
    send_data(@visitor.picture, type: 'image/png', disposition: 'inline')
  end


  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params.merge(picture: params[:visitor][:picture].read))

    respond_to do |format|
      if @visitor.save
        flash[:notice] = 'Visitor was saved!'

        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        flash[:error] = @visitor.errors

        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|      
      if @visitor.update(visitor_params.merge(picture: params[:visitor][:picture].read))
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:typeform_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
	def only_completed_survey_results(results)
		return results.select{|result| result["completed"]=="1"}
	end

	def get_visitor_id(visitor_token)
		associated_typeform = Typeform.find_by(token: visitor_token)
		visitor = Visitor.find_by(typeform_id: associated_typeform.id)
		unless visitor == nil
			return visitor.id
		else 
			return 1
		end
	end

	def survey_based_on_token(visitors, token)
		return visitors.select{|result| result["token"]==token}
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WestendAdminTools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitors/_form.html.erb
<%= form_for visitor, :html => { :multipart => true } do |f| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= f.label :typeform_id %><br>
      <%= f.select :typeform_id, Typeform.all.map { |tf| [tf.token, tf.id] }, {}, {class: 'form-control', include_blank: true} %>
    </div>
    <div class="form-group">
      <%= f.label 'Picture Upload - Please Keep Uploads below 1MB' %>
      <%= f.file_field :picture %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<div class="container">
	<h1>Editing Visitor</h1>

	<%= render 'form', visitor: @visitor %>

	<%= link_to 'Show', @visitor %> |
	<%= link_to 'Back', visitors_path %>
</div>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Home Address</th>
          <th>Gender</th>
          <th>Age Range</th>

          <th>More Info</th>
        </tr>
      </thead>

      <tbody>
        <% @visitorz.each do |visitor| %>
          <% visitor_id = get_visitor_id(visitor["token"]) %>
          <tr>

            <td><%= visitor["answers"]["textfield_26901017"] %></td>
            <td><%= visitor["answers"]["textfield_26901059"] %></td>
            <td><%= visitor["answers"]["textfield_26901167"] %></td>
            <td><%= visitor["answers"]["textfield_26901172"] %></td>
            <td><%= visitor["answers"]["textfield_26901204"] %></td>
            <td><%= visitor["answers"]["list_26900761_choice"] %></td>
            <td><%= visitor["answers"]["list_26900762_choice"] %></td> 

            <td><%= link_to 'Show', visitor_path(visitor_id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/visitors/new.html.erb
<div class="container">
	<h1>New Visitor</h1>

	<%= render 'form', visitor: @visitor %>

	<%= link_to 'Back', visitors_path %>
</div>

app/views/visitors/show.html.erb
<section class="breadcrumb-wrapper">
    <div class="container">
        <h2>Visitor</h2>
        <ol class="breadcrumb">
            <li><%= link_to "Visitors", visitors_path %></li>
            <li class="active"><%= @visitorr["answers"]["textfield_26901017"] %> <%= @visitorr["answers"]["textfield_26901059"] %></li>
        </ol>
    </div>
</section>

<p id="notice"><%= notice %></p>

				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @visitorr["answers"]["textfield_26901017"] %> <%= @visitorr["answers"]["textfield_26901059"] %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center">
                	<% if @visitor.picture.nil? %>
                		<img alt="Visitor Pic" src="http://canadatutors.ca/assets/pics/default-profile.png" class="img-circle img-responsive">
                	<% else %>
                		<%= image_tag visitor_picture_path(@visitor), class: "img-responsive", alt:"Visitor Pic" %>
                	<% end %>
                </div>

                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Typeform Token:</td>
                        <td style="word-break:break-all;"><%= @visitorr["token"] %></td>
                      </tr>
                      <tr>
                        <td>Phone</td>
                        <td><%= @visitorr["answers"]["textfield_26901167"] %></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><%= @visitorr["answers"]["textfield_26901172"] %></td>
                      </tr>
                      <tr>
                        <td>Home Address</td>
                        <td><%= @visitorr["answers"]["textfield_26901204"] %></td>
                      </tr>
                      <tr>
                        <td>Gender</td>
                        <td><%= @visitorr["answers"]["list_26900761_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Age Range</td>
                        <td><%= @visitorr["answers"]["list_26900762_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Times Visited This Church:</td>
                        <td><%= @visitorr["answers"]["list_26901296_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Country Born In:</td>
                        <td><%= @visitorr["answers"]["dropdown_26900767"] %></td>
                      </tr>
                      <tr>
                        <td>Ethnicity:</td>
                        <td><%= @visitorr["answers"]["list_26900763_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Marital Status:</td>
                        <td><%= @visitorr["answers"]["list_26900764_choice"] %></td>
                      </tr>
                      <tr>
                        <td># of people you live with:</td>
                        <td><%= @visitorr["answers"]["rating_26900769"] %></td>
                      </tr>
                      <tr>
                        <td>Most Used Form of Transportation:</td>
                        <td><%= @visitorr["answers"]["listimage_26900770_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Level of Education:</td>
                        <td><%= @visitorr["answers"]["list_26900765_choice"] %></td>
                      </tr>
                      <tr>
                        <td>Industry Working In:</td>
                        <td><%= @visitorr["answers"]["dropdown_26900768"] %></td>
                      </tr>                                                             
                      <tr>
                        <td>Income:</td>
                        <td><%= @visitorr["answers"]["list_26900766_choice"] %></td>
                      </tr>
                    </tbody>
                  </table>

							    <%= link_to "Add Or Edit Picture", edit_visitor_path(@visitor), class: "btn btn-lg btn-info" %>

							    <%= link_to "Delete", @visitor, class: "btn btn-lg btn-danger", method: "delete", data: { confirm: "Are you sure want to delete this visitor? This is a permanent removal." } %>

							    <%= link_to "Back", visitors_path, class: "btn btn-lg btn-default" %>

                </div>
              </div>
            </div>           
          </div>
        </div>